## Load Required Packages

In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

## Load the Dataset

In [2]:
df = pd.read_csv("Finance_data.csv")
df.shape

(21000, 27)

### Exploratory Data Analysis

In [3]:
df.head()

Income   Age  Dependents     Occupation City_Tier  \
0   44637.249636  49.0         0.0  SELf_EMPLoyEd     tier3   
1   26858.596592  -5.0         2.0        ReTIreD    Tier_2   
2   50367.605084  35.0         1.0        stUDENt    Tier_2   
3  101455.600247  21.0         NaN  SELf_EmpLoyed    Tier_3   
4   24875.283548  52.0         4.0   ProfESsIonAl    Tier_2   

                   Rent       Loan_Repayment          Insurance  \
0                   NaN                  0.0  2206.490129258186   
1     5371.719318345909                  0.0   869.522616973343   
2     7555.140762536515    4612.103386494076   2201.80004994864   
3  Rs15218.340037048692    6809.441426747919  4889.418087072337   
4     4975.056709546392  3112.6093984226027!    635.90717006727   

            Groceries           Transport  ... Desired_Savings  \
0   6658.768340572072  2636.9706962044347  ...     6200.537192   
1   2818.444460208314   1543.018777757239  ...     1923.176434   
2  6313.222080930132!   3221.396403447025  ...             NaN   
3  14690.149362877528    7106.13000500776  ...    16694.965136   
4  3034.3296645448127  1276.1551627316926  ...     1874.099434   

  Disposable_Income Potential_Savings_Groceries Potential_Savings_Transport  \
0      11265.627707                 1685.696222                  328.895281   
1       9676.818733                  540.306561                  119.347139   
2      13891.450624                 1466.073984                  473.549752   
3      31617.953615                 1875.932770                  762.020789   
4               NaN                  788.953124                   68.160766   

  Potential_Savings_Eating_Out Potential_Savings_Entertainment  \
0                   465.769172                      195.151320   
1                   141.866089                      234.131168   
2                   410.857129                      459.965256   
3                  1241.017448                      320.190594   
4                          NaN                      187.173750   

   Potential_Savings_Utilities  Potential_Savings_Healthcare  \
0                   678.292859                     67.682471   
1                   286.668408                      6.603212   
2                   488.383423                      7.290892   
3                  1389.815033                    193.502754   
4                   194.117130                     47.294591   

   Potential_Savings_Education  Potential_Savings_Miscellaneous  
0                     0.000000                        85.735517  
1                    56.306874                        97.388606  
2                   106.653597                       138.542422  
3                     0.000000                       296.041183  
4                    67.388120                        96.557076  

[5 rows x 27 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21000 entries, 0 to 20999
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Income                           21000 non-null  float64
 1   Age                              19953 non-null  float64
 2   Dependents                       19955 non-null  float64
 3   Occupation                       19946 non-null  object 
 4   City_Tier                        19944 non-null  object 
 5   Rent                             19956 non-null  object 
 6   Loan_Repayment                   19945 non-null  object 
 7   Insurance                        19952 non-null  object 
 8   Groceries                        19942 non-null  object 
 9   Transport                        19950 non-null  object 
 10  Eating_Out                       19946 non-null  object 
 11  Entertainment                    19956 non-null  object 
 12  Utilities         

In [5]:
df.describe()

Income           Age    Dependents  Desired_Savings_Percentage  \
count  2.100000e+04  19953.000000  19955.000000                19940.000000   
mean   4.154694e+04     38.718990      6.794337                    9.811693   
std    3.986602e+04     16.592333     21.193555                    3.911097   
min    1.301187e+03     -5.000000      0.000000                    5.000042   
25%    1.759116e+04     27.000000      1.000000                    6.940169   
50%    3.014334e+04     40.000000      2.000000                    8.896951   
75%    5.174281e+04     52.000000      3.000000                   11.886920   
max    1.079728e+06     64.000000    100.000000                   24.998776   

       Desired_Savings  Disposable_Income  Potential_Savings_Groceries  \
count     19945.000000       19957.000000                 19953.000000   
mean       4983.805584       10653.944827                   908.421407   
std        7754.857085       11743.015639                  1035.576729   
min           0.000000       -5400.788673                    16.575501   
25%        1224.040235        3780.074989                   316.269952   
50%        2156.698911        7239.881310                   604.813459   
75%        6214.124283       13351.572675                  1124.525614   
max      245504.485208      377060.218482                 34894.644404   

       Potential_Savings_Transport  Potential_Savings_Eating_Out  \
count                 19946.000000                  19943.000000   
mean                    473.410851                    254.279560   
std                     536.781466                    295.175415   
min                       8.268076                      3.797926   
25%                     161.824765                     84.712614   
50%                     307.780297                    165.222065   
75%                     589.162967                    312.510943   
max                   12273.258242                   5573.036433   

       Potential_Savings_Entertainment  Potential_Savings_Utilities  \
count                     19942.000000                 19955.000000   
mean                        253.839288                   433.653249   
std                         298.386294                   499.637373   
min                           3.121610                     6.200297   
25%                          84.665615                   147.604018   
50%                         164.152375                   283.833820   
75%                         310.936018                   535.988543   
max                        6222.200913                  8081.799518   

       Potential_Savings_Healthcare  Potential_Savings_Education  \
count                  19942.000000                 19949.000000   
mean                      41.379666                    62.334880   
std                       52.895701                    98.987082   
min                        0.001238                     0.000000   
25%                       11.061821                     4.915130   
50%                       25.118346                    33.085697   
75%                       52.278726                    80.678152   
max                     1394.531049                  3647.244243   

       Potential_Savings_Miscellaneous  
count                     19944.000000  
mean                        144.748814  
std                         169.823176  
min                           2.091973  
25%                          47.389567  
50%                          92.739492  
75%                         178.080157  
max                        4637.951137

In [6]:
# check missing values
df.isnull().sum()

Income                                0
Age                                1047
Dependents                         1045
Occupation                         1054
City_Tier                          1056
Rent                               1044
Loan_Repayment                     1055
Insurance                          1048
Groceries                          1058
Transport                          1050
Eating_Out                         1054
Entertainment                      1044
Utilities                          1040
Healthcare                         1044
Education                          1043
Miscellaneous                      1048
Desired_Savings_Percentage         1060
Desired_Savings                    1055
Disposable_Income                  1043
Potential_Savings_Groceries        1047
Potential_Savings_Transport        1054
Potential_Savings_Eating_Out       1057
Potential_Savings_Entertainment    1058
Potential_Savings_Utilities        1045
Potential_Savings_Healthcare       1058


In [7]:
#check duplicates
df.duplicated().sum()

1000

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20000 entries, 0 to 19999
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Income                           20000 non-null  float64
 1   Age                              19000 non-null  float64
 2   Dependents                       19000 non-null  float64
 3   Occupation                       19000 non-null  object 
 4   City_Tier                        19000 non-null  object 
 5   Rent                             19000 non-null  object 
 6   Loan_Repayment                   19000 non-null  object 
 7   Insurance                        19000 non-null  object 
 8   Groceries                        19000 non-null  object 
 9   Transport                        19000 non-null  object 
 10  Eating_Out                       19000 non-null  object 
 11  Entertainment                    19000 non-null  object 
 12  Utilities              

### Data Cleaning 

In [10]:
def clean_currency(x):
    if isinstance(x, str):
        # Remove non-numeric characters except decimal and minus
        clean_str = re.sub(r'[^0-9.-]', '', x)
        try:
            return float(clean_str)
        except ValueError:
            return np.nan
    return x

In [11]:
# Apply to Rent
if 'Rent' in df.columns:
    df['Rent'] = df['Rent'].apply(clean_currency)

In [12]:
df['Rent'].unique()

array([           nan,  5371.71931835,  7555.14076254, ...,
       18059.1545276 ,  8120.91347454, 35447.345172  ])

In [13]:
df['Rent'].dtype

dtype('float64')

In [14]:
# Apply to ALL potential numeric columns that might be object type
numeric_candidates = [
    'Loan_Repayment', 'Insurance', 'Groceries', 'Transport',
    'Eating_Out', 'Entertainment', 'Utilities', 'Healthcare',
    'Education', 'Miscellaneous', 'Disposable_Income', 
    'Desired_Savings', 'Desired_Savings_Percentage'
]
potential_cols = [c for c in df.columns if c.startswith("Potential_Savings")]
numeric_candidates += potential_cols

In [15]:
for col in numeric_candidates:
    if col in df.columns:
        # Check if column became object due to noise
        if df[col].dtype == 'object':
            df[col] = df[col].apply(clean_currency)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20000 entries, 0 to 19999
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Income                           20000 non-null  float64
 1   Age                              19000 non-null  float64
 2   Dependents                       19000 non-null  float64
 3   Occupation                       19000 non-null  object 
 4   City_Tier                        19000 non-null  object 
 5   Rent                             19000 non-null  float64
 6   Loan_Repayment                   19000 non-null  float64
 7   Insurance                        19000 non-null  float64
 8   Groceries                        19000 non-null  float64
 9   Transport                        19000 non-null  float64
 10  Eating_Out                       19000 non-null  float64
 11  Entertainment                    19000 non-null  float64
 12  Utilities              

In [17]:
# Normalize Categorical Columns
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df[col] = df[col].astype(str).str.lower().str.strip()
    df[col] = df[col].replace({'nan': np.nan, 'none': np.nan})

In [22]:
df['Age'].unique()

array([49., -5., 35., 21., 52., 57., 53., nan, 32., 30., 31., 54., 22.,
       39., 45., 55., 46., 37., 19., 47., 59., 56., 63., 27., 33., 23.,
       34., 58., 60., 24., 51., 43., 62., 28., 42., 50., 36., 20., 41.,
       38., 61., 48., 64., 44., 26., 18., 29., 25., 40.])

In [23]:
# clean age
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df = df[df['Age'].between(18, 90)]

In [24]:
df['Age'].unique()

array([49., 35., 21., 52., 57., 53., 32., 30., 31., 54., 22., 39., 45.,
       55., 46., 37., 19., 47., 59., 56., 63., 27., 33., 23., 34., 58.,
       60., 24., 51., 43., 62., 28., 42., 50., 36., 20., 41., 38., 61.,
       48., 64., 44., 26., 18., 29., 25., 40.])

In [25]:
df['Dependents'].unique()

array([  0.,   1.,  nan,   4.,   3.,   2., 100.])

In [26]:
# Clean Dependents
if 'Dependents' in df.columns:
    df['Dependents'] = pd.to_numeric(df['Dependents'], errors='coerce')
    df.loc[df['Dependents'] > 20, 'Dependents'] = np.nan

In [27]:
df['Dependents'].unique()

array([ 0.,  1., nan,  4.,  3.,  2.])

In [28]:
# Clean Negatives
numeric_cols = df.select_dtypes(include=[np.number]).columns
for col in numeric_cols:
    if col not in ['Income', 'Disposable_Income']:
        df[col] = df[col].clip(lower=0)

In [29]:
df.head()

Income   Age  Dependents     Occupation City_Tier          Rent  \
0   44637.249636  49.0         0.0  self_employed     tier3           NaN   
2   50367.605084  35.0         1.0        student    tier_2   7555.140763   
3  101455.600247  21.0         NaN  self_employed    tier_3  15218.340037   
4   24875.283548  52.0         4.0   professional    tier_2   4975.056710   
5   24875.610267  57.0         NaN  self_employed    tier_2   4975.122053   

   Loan_Repayment    Insurance     Groceries    Transport  ...  \
0        0.000000  2206.490129   6658.768341  2636.970696  ...   
2     4612.103386  2201.800050   6313.222081  3221.396403  ...   
3     6809.441427  4889.418087  14690.149363  7106.130005  ...   
4     3112.609398   635.907170   3034.329665  1276.155163  ...   
5        0.000000  1038.230996   3250.067756  1760.164812  ...   

   Desired_Savings  Disposable_Income  Potential_Savings_Groceries  \
0      6200.537192       11265.627707                  1685.696222   
2              NaN       13891.450624                  1466.073984   
3     16694.965136       31617.953615                  1875.932770   
4      1874.099434                NaN                   788.953124   
5      1478.666359        7599.265300                   957.619116   

   Potential_Savings_Transport  Potential_Savings_Eating_Out  \
0                   328.895281                    465.769172   
2                   473.549752                    410.857129   
3                   762.020789                   1241.017448   
4                    68.160766                           NaN   
5                   521.683848                    135.925865   

   Potential_Savings_Entertainment  Potential_Savings_Utilities  \
0                       195.151320                   678.292859   
2                       459.965256                   488.383423   
3                       320.190594                  1389.815033   
4                       187.173750                   194.117130   
5                       148.952326                    86.567256   

   Potential_Savings_Healthcare  Potential_Savings_Education  \
0                     67.682471                     0.000000   
2                      7.290892                   106.653597   
3                    193.502754                     0.000000   
4                     47.294591                    67.388120   
5                     13.143683                    33.961843   

   Potential_Savings_Miscellaneous  
0                        85.735517  
2                       138.542422  
3                       296.041183  
4                        96.557076  
5                        96.675925  

[5 rows x 27 columns]

In [30]:
df.tail()


Income   Age  Dependents     Occupation City_Tier          Rent  \
19995   40913.466178  51.0         4.0  self_employed    tier_1           NaN   
19996   90295.772638  21.0         NaN        student       NaN  18059.154528   
19997   40604.567373  30.0         1.0   professional    tier_2   8120.913475   
19998  118157.817240  27.0         2.0   professional    tier_1  35447.345172   
19999    8209.249769  62.0         3.0   professional    tier_1           NaN   

       Loan_Repayment    Insurance     Groceries    Transport  ...  \
19995     7703.854895  1646.799940   5477.403246  2084.230191  ...   
19996        0.000000  2770.589626  13118.222419  4633.108332  ...   
19997     8089.612716  1548.564328   6018.276121  2493.563674  ...   
19998    12345.910538  4735.672471  16392.438426  8248.242279  ...   
19999     1120.881704   276.376556    969.916908   460.435438  ...   

       Desired_Savings  Disposable_Income  Potential_Savings_Groceries  \
19995              NaN        1163.318310                   597.028412   
19996     10613.589598       30725.175170                  3854.823822   
19997      2267.905134        2267.905134                  1385.511100   
19998     10603.684814       10603.684814                  3217.771594   
19999       531.044006         860.350559                   261.160294   

       Potential_Savings_Transport  Potential_Savings_Eating_Out  \
19995                   287.315050                    347.658355   
19996                   359.602765                    911.269461   
19997                   379.927216                    138.209465   
19998                  2265.865033                    726.247719   
19999                   124.057428                     25.940556   

       Potential_Savings_Entertainment  Potential_Savings_Utilities  \
19995                       145.843671                   212.833325   
19996                       424.064224                  1555.548024   
19997                       297.695658                   824.565267   
19998                       273.912367                   859.230004   
19999                        35.238134                    94.909265   

       Potential_Savings_Healthcare  Potential_Savings_Education  \
19995                     44.900294                          NaN   
19996                    129.655981                   239.445622   
19997                     57.891000                    72.728663   
19998                     98.961780                    92.189012   
19999                      1.685026                     4.837574   

       Potential_Savings_Miscellaneous  
19995                       190.591917  
19996                       351.436046  
19997                       122.569277  
19998                       569.811212  
19999                        12.766302  

[5 rows x 27 columns]

In [33]:
df['Occupation'].unique()

array(['self_employed', 'student', 'professional', nan, 'retired'],
      dtype=object)

In [34]:
df['City_Tier'].unique()

array(['tier3', 'tier_2', 'tier_3', 'tier_1', '1', 'tier2', 'tier1', '2',
       nan, '3'], dtype=object)

In [35]:
df['Rent'].unique()

array([           nan,  7555.14076254, 15218.34003705, ...,
       18059.1545276 ,  8120.91347454, 35447.345172  ])

In [37]:
df['City_Tier'].value_counts()

City_Tier
tier_2    6359
tier_1    4032
tier_3    2250
tier2      790
3          762
1          760
tier3      752
tier1      733
2          695
Name: count, dtype: int64

In [38]:
mapping = {
    "tier3": "tier_3",
    "tier2": "tier_2",
    "tier1": "tier_1",
    "1": "tier_1",
    "2": "tier_2",
    "3": "tier_3"
}
df["City_Tier"] = df["City_Tier"].replace(mapping)

In [39]:
df['City_Tier'].value_counts()

City_Tier
tier_2    7844
tier_1    5525
tier_3    3764
Name: count, dtype: int64

In [41]:
df['City_Tier'].unique()

array(['tier_3', 'tier_2', 'tier_1', nan], dtype=object)

In [42]:
df['Occupation'].value_counts()

Occupation
retired          4304
professional     4302
student          4280
self_employed    4275
Name: count, dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18049 entries, 0 to 19999
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Income                           18049 non-null  float64
 1   Age                              18049 non-null  float64
 2   Dependents                       16299 non-null  float64
 3   Occupation                       17161 non-null  object 
 4   City_Tier                        17133 non-null  object 
 5   Rent                             17140 non-null  float64
 6   Loan_Repayment                   17142 non-null  float64
 7   Insurance                        17152 non-null  float64
 8   Groceries                        17155 non-null  float64
 9   Transport                        17141 non-null  float64
 10  Eating_Out                       17154 non-null  float64
 11  Entertainment                    17160 non-null  float64
 12  Utilities              

In [44]:
df.isnull().sum()

Income                                0
Age                                   0
Dependents                         1750
Occupation                          888
City_Tier                           916
Rent                                909
Loan_Repayment                      907
Insurance                           897
Groceries                           894
Transport                           908
Eating_Out                          895
Entertainment                       889
Utilities                           904
Healthcare                          905
Education                           908
Miscellaneous                       891
Desired_Savings_Percentage          907
Desired_Savings                     901
Disposable_Income                   897
Potential_Savings_Groceries         900
Potential_Savings_Transport         889
Potential_Savings_Eating_Out        905
Potential_Savings_Entertainment     905
Potential_Savings_Utilities         894
Potential_Savings_Healthcare        904


In [45]:
df.describe()

Income           Age    Dependents           Rent  \
count  1.804900e+04  18049.000000  16299.000000   17140.000000   
mean   4.141652e+04     41.001274      1.997423    9053.430945   
std    3.995533e+04     13.568738      1.419235    9051.944150   
min    1.301187e+03     18.000000      0.000000     235.365692   
25%    1.762334e+04     29.000000      1.000000    3656.278541   
50%    3.007685e+04     41.000000      2.000000    6388.224578   
75%    5.133754e+04     53.000000      3.000000   11228.460154   
max    1.079728e+06     64.000000      4.000000  151482.291055   

       Loan_Repayment     Insurance      Groceries     Transport  \
count    17142.000000  17152.000000   17155.000000  17141.000000   
mean      2055.991881   1450.478614    5176.446867   2690.060428   
std       4299.666386   1497.883342    4971.851714   2664.059170   
min          0.000000     30.002012     154.078240     81.228584   
25%          0.000000    579.236110    2158.577098   1121.997311   
50%          0.000000   1014.902637    3725.332288   1926.748033   
75%       2626.683070   1777.655047    6446.779213   3341.270553   
max     123080.682009  38734.932935  119816.898124  81861.503457   

         Eating_Out  Entertainment  ...  Desired_Savings  Disposable_Income  \
count  17154.000000   17160.000000  ...     17148.000000       17152.000000   
mean    1453.752388    1440.489296  ...      4965.709321       10602.243952   
std     1474.411378    1480.178019  ...      7792.976582       11733.504864   
min       39.437523      45.421469  ...         0.000000       -5400.788673   
25%      579.069882     582.988494  ...      1225.416174        3780.592607   
50%     1026.851838    1017.486132  ...      2158.479229        7226.877936   
75%     1794.593867    1777.684168  ...      6184.731113       13262.480890   
max    34406.100166   38667.368308  ...    245504.485208      377060.218482   

       Potential_Savings_Groceries  Potential_Savings_Transport  \
count                 17149.000000                 17160.000000   
mean                    905.608052                   471.532614   
std                    1035.967890                   538.438456   
min                      16.575501                     8.268076   
25%                     316.762585                   161.785299   
50%                     603.948694                   307.318829   
75%                    1121.025383                   585.514035   
max                   34894.644404                 12273.258242   

       Potential_Savings_Eating_Out  Potential_Savings_Entertainment  \
count                  17144.000000                     17144.000000   
mean                     254.610678                       252.380731   
std                      297.207988                       295.798990   
min                        3.797926                         3.121610   
25%                       84.423263                        84.777463   
50%                      164.238820                       163.722383   
75%                      312.002670                       310.900778   
max                     5573.036433                      6222.200913   

       Potential_Savings_Utilities  Potential_Savings_Healthcare  \
count                 17155.000000                  17145.000000   
mean                    432.867644                     41.191122   
std                     499.877002                     52.794036   
min                       6.200297                      0.001238   
25%                     147.260098                     11.016263   
50%                     284.643767                     25.110512   
75%                     533.677833                     52.032491   
max                    8081.799518                   1394.531049   

       Potential_Savings_Education  Potential_Savings_Miscellaneous  
count                 17158.000000                     17140.000000  
mean                     62.518972                       144.013931  
std              

### Feature Engineering

In [46]:
if potential_cols:
    # Fill NaNs with 0 temporarily for summation
    df[potential_cols] = df[potential_cols].fillna(0)
    df["Total_Potential_Savings"] = df[potential_cols].sum(axis=1)
    
    # Remove extreme outliers in Target
    q_high = df["Total_Potential_Savings"].quantile(0.99)
    df = df[df["Total_Potential_Savings"] <= q_high]
    print("Target variable calculated.")

Target variable calculated.


In [75]:
df.to_csv("cleaned_dataset.csv", index=False)
print("\nSaved cleaned dataset to finance_dataset_cleaned.csv")


Saved cleaned dataset to finance_dataset_cleaned.csv
